//go:build integration

package networkmap_pgsql

import (
	"context"
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	networkmapdb "github.com/netbirdio/netbird/management/internals/network_map_db"
	"github.com/netbirdio/netbird/management/server/integrations/integrated_validator"
	"github.com/netbirdio/netbird/management/server/settings"
	"github.com/netbirdio/netbird/management/server/types"
	"github.com/netbirdio/netbird/shared/management/networkmap/nmdata"
	log "github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"go.uber.org/mock/gomock"
)

//go:embed network_map_data.sql
var nmapData string

//go:embed network_map_data_golden.json
var goldenNMap string

const EnvUpdateGoldenData = "NMAP_UPDATE_GOLDEN_DATA"

func TestGetNetworkMapData(t *testing.T) {
	ctx := context.TODO()

	// The two mocks are generated by different mock frameworks, so each needs a
	// controller of its own kind.
	extraSettingsManager := settings.NewMockManager(gomock.NewController(t))
	extraSettingsManager.EXPECT().GetExtraSettings(gomock.Any(), gomock.Any()).Return(&types.ExtraSettings{}, nil).AnyTimes()

	peerValidators := integrated_validator.NewMockIntegratedValidator(gomock.NewController(t))
	peerValidators.EXPECT().GetValidatedPeers(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(
		map[string]struct{}{
			"peer-id-1": {},
			"peer-id-2": {},
			"peer-id-3": {},
		}, nil).AnyTimes()

	storeImpl := networkmapdb.NetworkMapDBStoreImpl{
		Store:                   store(t),
		ExtraSettingsManager:    extraSettingsManager,
		IntegratedPeerValidator: peerValidators,
	}

	for _, query := range strings.Split(nmapData, ";") {
		if err := store(t).Exec(ctx, query); err != nil {
			log.Fatalf("error initializing nmap test: %s", err.Error())
		}
	}

	nmap, err := storeImpl.GetNetworkMapData(ctx, "account-33")
	assert.NoError(t, err)

	serializedNMap, err := json.MarshalIndent(nmap, "", "  ")
	assert.NoError(t, err)

	if _, ok := os.LookupEnv(EnvUpdateGoldenData); ok {
		_, filename, _, _ := runtime.Caller(0)
		tosavepath := filepath.Join(filepath.Dir(filename), "network_map_data_golden.json")
		err = os.WriteFile(tosavepath, serializedNMap, 0644)
		assert.NoError(t, err)
		goldenNMap = string(serializedNMap)
	}
	assert.Equal(t, goldenNMap, string(serializedNMap))

	// Exercise the persisted SQLite -> NetworkMapData -> per-peer DNS path.
	// The fixture assigns peer-id-331 to 33-group-one-resource-id and assigns
	// both persisted nameserver groups to that distribution group.
	nmap.ValidatedPeers["peer-id-331"] = struct{}{}
	components := nmap.GetPeerNetworkMapComponents("peer-id-331", nmdata.CustomZone{})
	assert.NotEmpty(t, components.NameServerGroups, "persisted nameserver groups must reach peer components")
	calculated := components.Calculate(ctx)
	assert.True(t, calculated.DNSConfig.ServiceEnable, "DNS management must stay enabled for the peer")
	assert.NotEmpty(t, calculated.DNSConfig.NameServerGroups, "persisted nameserver groups must survive calculation")


	// group_id is globally unique, so a stale denormalized account_id on the
	// membership row must not make the group appear empty to network-map reads.
	execQuery(t, ctx, `update group_peers set account_id='stale-account' where group_id='33-group-one-resource-id' and peer_id='peer-id-331'`)
	defer execQuery(t, ctx, `update group_peers set account_id='account-33' where group_id='33-group-one-resource-id' and peer_id='peer-id-331'`)

	staleNMap, err := storeImpl.GetNetworkMapData(ctx, "account-33")
	assert.NoError(t, err)
	staleNMap.ValidatedPeers["peer-id-331"] = struct{}{}
	staleComponents := staleNMap.GetPeerNetworkMapComponents("peer-id-331", nmdata.CustomZone{})
	assert.NotEmpty(t, staleComponents.NameServerGroups,
		"nameserver delivery must not depend on redundant group_peers.account_id")
}